CREATE DATABASE IF NOT EXISTS DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_SEXOS(
	SEX_CODIGO TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	SEX_NOME VARCHAR(15) NOT NULL,
	SEX_SIGLA CHAR(1) NOT NULL,
	CONSTRAINT PRIMARY KEY(SEX_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_UFS(
	UFS_CODIGO TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	UFS_UF VARCHAR(30) NOT NULL,
	UFS_SIGLA CHAR(2) NOT NULL,
	CONSTRAINT PRIMARY KEY(UFS_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_CIDADES(
	CID_CODIGO SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	CID_UFS_CODIGO TINYINT UNSIGNED NOT NULL,
	CID_CIDADE VARCHAR(30) NOT NULL,
	CONSTRAINT PRIMARY KEY(CID_CODIGO),
	CONSTRAINT FK_UFS_CID FOREIGN KEY(CID_UFS_CODIGO) REFERENCES TB_UFS(UFS_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_BAIRROS(
	BAI_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
	BAI_BAIRRO VARCHAR(30) NOT NULL,
	BAI_CID_CODIGO SMALLINT UNSIGNED NOT NULL,
	CONSTRAINT PRIMARY KEY(BAI_CODIGO),
	CONSTRAINT FK_CID_BAI FOREIGN KEY(BAI_CID_CODIGO) REFERENCES TB_CIDADES(CID_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_CLIENTES(
	CLI_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
	CLI_NOME VARCHAR(50) NOT NULL,
	CLI_CPF CHAR(11) NOT NULL,
	CLI_NASCIMENTO DATE NOT NULL,
	CLI_LOGRADOURO VARCHAR(80) NOT NULL,
	CLI_NUMERO VARCHAR(15),
	CLI_COMPLEMENTO VARCHAR(20),
	CLI_CEP CHAR(8) NOT NULL,
	CLI_SEX_CODIGO TINYINT UNSIGNED NOT NULL,
	CLI_BAI_CODIGO INT UNSIGNED NOT NULL,
	CONSTRAINT PRIMARY KEY(CLI_CODIGO),
	CONSTRAINT FK_SEX_CLI FOREIGN KEY(CLI_SEX_CODIGO) REFERENCES TB_SEXOS(SEX_CODIGO),
	CONSTRAINT FK_BAI_CLI FOREIGN KEY(CLI_BAI_CODIGO) REFERENCES TB_BAIRROS(BAI_CODIGO) 
);

CREATE TABLE IF NOT EXISTS TB_FONES_CLIENTES(
	FDC_CLI_CODIGO INT UNSIGNED NOT NULL,
	FDC_FONE VARCHAR(11) NOT NULL,
	CONSTRAINT PRIMARY KEY(FDC_CLI_CODIGO, FDC_FONE),
	CONSTRAINT FK_CLI_FDC FOREIGN KEY(FDC_CLI_CODIGO) REFERENCES TB_CLIENTES(CLI_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_EMAILS_CLIENTES(
	EDC_CLI_CODIGO INT UNSIGNED NOT NULL,
	EDC_EMAIL VARCHAR(200) NOT NULL,
	CONSTRAINT PRIMARY KEY(EDC_CLI_CODIGO, EDC_EMAIL),
	CONSTRAINT FK_CLI_EDC FOREIGN KEY(EDC_CLI_CODIGO) REFERENCES TB_CLIENTES(CLI_CODIGO)
);
CREATE TABLE IF NOT EXISTS TB_DEPENDENTES(
	DEP_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
	DEP_NOME VARCHAR(50) NOT NULL,
	DEP_NASCIMENTO DATE NOT NULL,
	DEP_CPF CHAR(11) NOT NULL,
	CONSTRAINT PRIMARY KEY(DEP_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_PARENTESCO(
	PAR_CODIGO TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	PAR_PARENTESCO VARCHAR(20) NOT NULL,
	CONSTRAINT PRIMARY KEY(PAR_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_DEPENDENTES_CLIENTES(
	DDC_CLI_CODIGO INT UNSIGNED NOT NULL,
	DDC_DEP_CODIGO INT UNSIGNED NOT NULL,
	DDC_PAR_CODIGO TINYINT UNSIGNED NOT NULL,
	CONSTRAINT PRIMARY KEY(DDC_CLI_CODIGO, DDC_DEP_CODIGO),
	CONSTRAINT FK_CLI_DDC FOREIGN KEY(DDC_CLI_CODIGO) REFERENCES TB_CLIENTES(CLI_CODIGO),
	CONSTRAINT FK_DEP_DDC FOREIGN KEY(DDC_DEP_CODIGO) REFERENCES TB_DEPENDENTES(DEP_CODIGO),
	CONSTRAINT FK_PAR_DDC FOREIGN KEY(DDC_PAR_CODIGO) REFERENCES TB_PARENTESCO(PAR_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_ATENDENTES(
	ATE_MATRICULA INT UNSIGNED NOT NULL AUTO_INCREMENT,
	ATE_SEX_CODIGO TINYINT UNSIGNED NOT NULL,
	ATE_NOME VARCHAR(50) NOT NULL,
	ATE_ADMISSAO DATE NOT NULL,
	ATE_DEMISSAO DATE,
	CONSTRAINT PRIMARY KEY(ATE_MATRICULA),
	CONSTRAINT FK_SEX_ATE FOREIGN KEY(ATE_SEX_CODIGO) REFERENCES TB_SEXOS(SEX_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_FONES_ATENDENTES(
	FDA_ATE_MATRICULA INT UNSIGNED NOT NULL,
	FDA_FONE VARCHAR(11) NOT NULL,
	CONSTRAINT PRIMARY KEY(FDA_ATE_MATRICULA, FDA_FONE),
	CONSTRAINT FK_ATE_FDA FOREIGN KEY(FDA_ATE_MATRICULA) REFERENCES TB_ATENDENTES(ATE_MATRICULA)
);

CREATE TABLE IF NOT EXISTS TB_EMAILS_ATENDENTES(
	EDA_ATE_MATRICULA INT UNSIGNED NOT NULL,
	EDA_EMAIL VARCHAR(200) NOT NULL,
	CONSTRAINT PRIMARY KEY(EDA_ATE_MATRICULA, EDA_EMAIL),
	CONSTRAINT FK_ATE_EDA FOREIGN KEY(EDA_ATE_MATRICULA) REFERENCES TB_ATENDENTES(ATE_MATRICULA)
);

CREATE TABLE IF NOT EXISTS TB_LOCACOES(
	LOC_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
	LOC_ATE_MATRICULA INT UNSIGNED NOT NULL,
	LOC_CLI_CODIGO INT UNSIGNED NOT NULL,
	LOC_DT_LOC DATE NOT NULL,
	LOC_VALOR FLOAT NOT NULL,
	CONSTRAINT PRIMARY KEY(LOC_CODIGO),
	CONSTRAINT FK_CLI_LOC FOREIGN KEY(LOC_CLI_CODIGO) REFERENCES TB_CLIENTES(CLI_CODIGO),
	CONSTRAINT FK_ATE_LOC FOREIGN KEY(LOC_ATE_MATRICULA) REFERENCES TB_ATENDENTES(ATE_MATRICULA)
);

CREATE TABLE IF NOT EXISTS TB_STATUS(
	STA_CODIGO TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	STA_STATUS VARCHAR(10) NOT NULL,
	CONSTRAINT PRIMARY KEY(STA_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_MIDIAS(
	MID_CODIGO TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	MID_MIDIA VARCHAR(10) NOT NULL,
	CONSTRAINT PRIMARY KEY(MID_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_CATEGORIAS(
	CAT_CODIGO TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	CAT_CATEGORIA VARCHAR(20) NOT NULL,
	CAT_VALOR FLOAT NOT NULL,
	CONSTRAINT PRIMARY KEY(CAT_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_PAISES(
	PAI_CODIGO SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	PAI_PAIS VARCHAR(30) NOT NULL,
	PAI_SIGLA CHAR(3) NOT NULL,
	CONSTRAINT PRIMARY KEY(PAI_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_CLASSIFICACOES(
	CLA_CODIGO TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	CLA_CLASSIFICACAO VARCHAR(20) NOT NULL,
	CLA_SIGLA CHAR(7) NOT NULL,
	CONSTRAINT PRIMARY KEY(CLA_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_FILMES(
	FIL_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
	FIL_CAT_CODIGO TINYINT UNSIGNED NOT NULL,
	FIL_CLA_CODIGO TINYINT UNSIGNED NOT NULL,
	FIL_PAI_CODIGO SMALLINT UNSIGNED NOT NULL,
	FIL_TITULO VARCHAR(50) NOT NULL,
	FIL_SINOPSE VARCHAR(5000) NOT NULL,
	FIL_DURACAO INT UNSIGNED NOT NULL,
	FIL_LANCAMENTO INT UNSIGNED NOT NULL,
	CONSTRAINT PRIMARY KEY(FIL_CODIGO),
	CONSTRAINT FK_PAI_FIL FOREIGN KEY(FIL_PAI_CODIGO) REFERENCES TB_PAISES(PAI_CODIGO),
	CONSTRAINT FK_CLA_FIL FOREIGN KEY(FIL_CLA_CODIGO) REFERENCES TB_CLASSIFICACOES(CLA_CODIGO),
	CONSTRAINT FK_CAT_FIL FOREIGN KEY(FIL_CAT_CODIGO) REFERENCES TB_CATEGORIAS(CAT_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_COPIAS(
	COP_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
	COP_STA_CODIGO TINYINT UNSIGNED NOT NULL,
	COP_MID_CODIGO TINYINT UNSIGNED NOT NULL,
	COP_FIL_CODIGO INT UNSIGNED NOT NULL,
	COP_OBSERVACAO VARCHAR(5000),
	CONSTRAINT PRIMARY KEY(COP_CODIGO),
	CONSTRAINT FK_FIL_COP FOREIGN KEY(COP_FIL_CODIGO) REFERENCES TB_FILMES(FIL_CODIGO),
	CONSTRAINT FK_MID_COP FOREIGN KEY(COP_MID_CODIGO) REFERENCES TB_MIDIAS(MID_CODIGO),
	CONSTRAINT FK_STA_COP FOREIGN KEY(COP_STA_CODIGO) REFERENCES TB_STATUS(STA_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_ITENS_LOCACOES(
	IDL_LOC_CODIGO INT UNSIGNED NOT NULL,
	IDL_COP_CODIGO INT UNSIGNED NOT NULL,
	IDL_DT_DEV DATE,
	IDL_VALOR FLOAT,
	CONSTRAINT PRIMARY KEY(IDL_LOC_CODIGO, IDL_COP_CODIGO),
	CONSTRAINT FK_LOC_IDL FOREIGN KEY(IDL_LOC_CODIGO) REFERENCES TB_LOCACOES(LOC_CODIGO),
	CONSTRAINT FK_COP_IDL FOREIGN KEY(IDL_COP_CODIGO) REFERENCES TB_COPIAS(COP_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_IDIOMAS(
	IDI_CODIGO SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	IDI_IDIOMA VARCHAR(20) NOT NULL,
	IDI_SIGLA VARCHAR(5) NOT NULL,
	CONSTRAINT PRIMARY KEY(IDI_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_LEGENDAS(
	LEG_IDI_CODIGO SMALLINT UNSIGNED NOT NULL,
	LEG_COP_CODIGO INT UNSIGNED NOT NULL,
	CONSTRAINT PRIMARY KEY(LEG_IDI_CODIGO, LEG_COP_CODIGO),
	CONSTRAINT FK_IDI_LEG FOREIGN KEY(LEG_IDI_CODIGO) REFERENCES TB_IDIOMAS(IDI_CODIGO),
	CONSTRAINT FK_COP_LEG FOREIGN KEY(LEG_COP_CODIGO) REFERENCES TB_COPIAS(COP_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_AUDIOS(
	AUD_IDI_CODIGO SMALLINT UNSIGNED NOT NULL,
	AUD_COP_CODIGO INT UNSIGNED NOT NULL,
	CONSTRAINT PRIMARY KEY(AUD_IDI_CODIGO, AUD_COP_CODIGO),
	CONSTRAINT FK_IDI_AUD FOREIGN KEY(AUD_IDI_CODIGO) REFERENCES TB_IDIOMAS(IDI_CODIGO),
	CONSTRAINT FK_COP_AUD FOREIGN KEY(AUD_COP_CODIGO) REFERENCES TB_COPIAS(COP_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_ATORES(
	ATO_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
	ATO_ATOR VARCHAR(50) NOT NULL,
	CONSTRAINT PRIMARY KEY(ATO_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_GENEROS(
	GEN_CODIGO TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	GEN_GENERO VARCHAR(20) NOT NULL,
	CONSTRAINT PRIMARY KEY(GEN_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_DIRETORES(
	DIR_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
	DIR_DIRETOR VARCHAR(50) NOT NULL,
	CONSTRAINT PRIMARY KEY(DIR_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_ATORES_FILMES(
	ADF_FIL_CODIGO INT UNSIGNED NOT NULL,
	ADF_ATO_CODIGO INT UNSIGNED NOT NULL,
	CONSTRAINT PRIMARY KEY(ADF_FIL_CODIGO, ADF_ATO_CODIGO),
	CONSTRAINT FK_FIL_ADF FOREIGN KEY(ADF_FIL_CODIGO) REFERENCES TB_FILMES(FIL_CODIGO),
	CONSTRAINT FK_ATO_ADF FOREIGN KEY(ADF_ATO_CODIGO) REFERENCES TB_ATORES(ATO_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_GENEROS_FILMES(
	GDF_FIL_CODIGO INT UNSIGNED NOT NULL,
	GDF_GEN_CODIGO TINYINT UNSIGNED NOT NULL,
	CONSTRAINT PRIMARY KEY(GDF_FIL_CODIGO, GDF_GEN_CODIGO),
	CONSTRAINT FK_FIL_GDF FOREIGN KEY(GDF_FIL_CODIGO) REFERENCES TB_FILMES(FIL_CODIGO),
	CONSTRAINT FK_GEN_GDF FOREIGN KEY(GDF_GEN_CODIGO) REFERENCES TB_GENEROS(GEN_CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_DIRETORES_FILMES(
	DDF_FIL_CODIGO INT UNSIGNED NOT NULL,
	DDF_DIR_CODIGO INT UNSIGNED NOT NULL,
	CONSTRAINT PRIMARY KEY(DDF_FIL_CODIGO, DDF_DIR_CODIGO),
	CONSTRAINT FK_FIL_DDF FOREIGN KEY(DDF_FIL_CODIGO) REFERENCES TB_FILMES(FIL_CODIGO),
	CONSTRAINT FK_DIR_DDF FOREIGN KEY(DDF_DIR_CODIGO) REFERENCES TB_DIRETORES(DIR_CODIGO)
);
